### ISSUE TITLE
Creating new Linux VM with SSH key and no password throws error

### ISSUE THREAD

**Issue by dbarentine** [Azure/azure-xplat-cli#2506] opened 2016-02-04 22:48 UTC
Error: Authentication using either SSH or by user name and password must be enabled in Linux profile.
  <<< async stack >>>
  at createOrUpdateVM__14 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine._js:198:82)
  at createVM__1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js:163:20)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/vm/vm._js:132:16)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-compute/lib/operations/virtualMachines.js:907:19
    at retryCallback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest-azure/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest-azure/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/local/lib/node_modules/azure-cli/lib/util/utils.js:482:7
    at handleRedirect (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:459:9)
    at /usr/local/lib/node_modules/azure-cli/lib/util/logging.js:401:7
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest-azure/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:344:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:1239:14)

I was using these parameters:
--admin-username core \
--ssh-publickey-file id_rsa.pub \

Version 0.9.15 of the CLI.

It appears that what is happening is in the CLI osProfile for Linux the SSH key is being set in a value called sshConfiguration. But the underlying SDK model specifically linuxConfiguration.js is expecting this to be called ssh. And so when the osProfile gets serialized against the model the sshKeys get dropped.

**Comment by amarzavery** [comment] 2016-02-04 23:24
@dbarentine - Thanks for filing this issue and for finding the root cause. The underlying node sdk is now being auto generated by a new generator named AutoRest. In release 0.9.15 the vm commands were ported to consume the newly generated sdk. This scenario was not covered in the tests. This has been fixed in this PR https://github.com/Azure/azure-xplat-cli/pull/2508

**Closed** 2016-02-05 01:12 UTC
Labels: IAAS
