### ISSUE TITLE
azure VM image list-publishers errors with "Cannot find module 'is-stream'"

### ISSUE THREAD

**Issue by mvkleeff** [Azure/azure-xplat-cli#3632] opened 2017-07-05 11:19 UTC
#CLI Version: **0.10.14**
OS Type: Win
Installation via:  win installer

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure vm image list-publishers -l "West US"` command outputs 'Cannot find module 'is-stream''.

Steps to reproduce:
1) Run `azure vm image list-publishers -l "West US" `

Error stack trace:

**2017-07-05T13:06:20.653Z:
{ Error: Cannot find module 'is-stream'
  <<< async stack >>>
  <<< raw stack >>>
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-arm-compute\node_modules\ms-rest\lib\serialization.js:7:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
  stack: [Getter/Setter],
  code: 'MODULE_NOT_FOUND',
  __frame: undefined,
  rawStack: [Getter] }
Error: Cannot find module 'is-stream'
  <<< async stack >>>
  <<< raw stack >>>
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-arm-compute\node_modules\ms-rest\lib\serialization.js:7:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
**

**Comment by number213** [comment] 2017-07-05 11:24
Please see: https://github.com/Azure/azure-xplat-cli/issues/3624#issuecomment-311789820

**Comment by mvkleeff** [comment] 2017-07-05 11:52
I hope it will be fixed with that release, we had an other issue with is-stream, which was solved by using an updated package.json from https://github.com/balajikris/azure-xplat-cli/blob/0cf10abf042c6725ba0bda9d39d7d964ec74dc78/package.json
However, I did test with dev and batch-beta pulls, and experienced the same issue on this specific VM list part.

**Comment by balajikris** [comment] 2017-07-06 18:18
@mvkleeff -- 

1. are you saying that you continued to experience the same error after taking that package.json and running npm install on your branch? 
2. can you try installing the last release `0.10.14` from npm and see if you still run into that error?

Knowing these would help us a lot. I tried to repro this, but found only one scenario as mentioned in #3624 and I believe I've fixed that.

**Comment by balajikris** [comment] 2017-07-06 18:29
Okay I can confirm this much - 

With my changes linked to #3624 (one PR to touch package.json and another PR to improve the windows installer), I built a windows installer for this app locally and installed it. With that version installed, I see that this command works as expected. 

@mvkleeff -- If you have my package.json change and if you've npm installed it and are running from code, I expect your scenario to work without issues. If it doesn't, please let me know.

**Comment by balajikris** [comment] 2017-07-06 18:30
potential dupe of #3624

**Comment by balajikris** [comment] 2017-07-10 20:26
Currently testing the 0.10.15 installer and this command now works as expected. :shipit:

**Comment by balajikris** [comment] 2017-07-14 19:22
0.10.15 is now publicly available and this bug is now fixed.

**Closed by balajikris** 2017-07-14 19:22 UTC
