### ISSUE TITLE
[AzureChinaCloud][ARM] Failed to create a linux VM because of unsupported api-versions 

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2824] opened 2016-04-27 08:10 UTC
CLI Version: **0.9.20**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Description:
`azure vm create` command can't create a linux VM with the following error output.

```
+ Creating VM "binxi042702-devbox"
error:   No registered resource provider found for location 'chinaeast' and API version '2016-03-30' for type 'virtualMachines'. The supported api-versions are '2015-05-01-preview, 2015-06-15'. The supported locations are 'chinanorth, chinaeast'.
```

Steps to reproduce:
1) Run `azure login --environment AzureChinaCloud`
2) Then run `azure vm create ...`

Error stack trace:

```
2016-04-27T08:04:36.497Z:
{ [Error: No registered resource provider found for location 'chinaeast' and API version '2016-03-30' for type 'virtualMachines'. The supported api-versions are '2015-05-01-preview, 2015-06-15'. The supported locations are 'chinanorth, chinaeast'.]
  stack: [Getter/Setter],
  statusCode: 400,
  request:
   { rawResponse: false,
     queryString: {},
     method: 'PUT',
     headers:
      { 'x-ms-client-request-id': '130c56e5-82f2-46e3-b2b4-8082ef3cc692',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'user-agent': 'WindowsAzureXplatCLI/0.9.20' },
     url: 'https://management.chinacloudapi.cn/subscriptions/824e43b7-4be9-435e-8c2a-26493d7597aa/resourceGroups/binxi042702/providers/Microsoft.Compute/virtualMachines/binxi042702-devbox?api-version=2016-03-30',
     body: '{"location":"chinaeast","tags":{},"properties":{"hardwareProfile":{"vmSize":"Standard_A1"},"storageProfile":{"imageReference":{"publisher":"canonical","offer":"UbuntuServer","sku":"14.04.3-LTS","version":"latest"},"osDisk":{"name":"clibf6a960c9d028249-os-1461744270778","vhd":{"uri":"https://binxi042702sa.blob.core.chinacloudapi.cn/vhds/clibf6a960c9d028249-os-1461744270778.vhd"},"caching":"ReadWrite","createOption":"FromImage"}},"osProfile":{"computerName":"binxi042702-devbox","adminUsername":"azureuser","linuxConfiguration":{"disablePasswordAuthentication":true,"ssh":{"publicKeys":[{"path":"/home/azureuser/.ssh/authorized_keys","keyData":"MIIBrTCCAZigAwIBAgIBATALBgkqhkiG9w0BAQUwADAiGA8yMDE2MDQyNzA3NTQz\\r\\nMFoYDzIwMjYwNDI3MDc1NDMwWjA1MQswCQYDVQQGEwJERTEWMBQGA1UECgwNZHVt\\r\\nbXktc3ViamVjdDEOMAwGA1UEAwwFZHVtbXkwggEiMA0GCSqGSIb3DQEBAQUAA4IB\\r\\nDwAwggEKAoIBAQC9XsLA2DdesxEDuo+rH2x4Ga/v8kLGICLfe7kBGVnjCLbQNBgG\\r\\n3nkRUb9g9dJ0a6KxSxD59889vNdHaMtiYrlX16FiGwMoxTtttqnYvgSrP+Nga+Id\\r\\nAenJrD+VNwWSpCK+K9+MBWL5W0g42n6ZmeW5Mt5fp+9J2kjEUf1EwgjHM5GSccAB\\r\\nrnSOV7++Ddr3Pp+92FZJQbq6HcDP60ZheO6Fe39CTzxVkbCYRPONQL1RkLPtqsU4\\r\\nkytKjaLB9fuByHJcULrYjehXxForUbBqn1F0RDpyUGFHKK5prsCTMhYwKgZaGYqY\\r\\nTq16mkmcjRFVwV4bsVuSuOCBFh5GEVQe4uJFAgMBAAEwCwYJKoZIhvcNAQEFAwIA\\r\\nAA==\\r\\n"}]}}},"networkProfile":{"networkInterfaces":[{"id":"/subscriptions/824e43b7-4be9-435e-8c2a-26493d7597aa/resourceGroups/binxi042702/providers/Microsoft.Network/networkInterfaces/binxi042702-devbox"}]},"diagnosticsProfile":{"bootDiagnostics":{"enabled":true,"storageUri":"https://binxi042702sa.blob.core.chinacloudapi.cn/"}}}}' },
  response:
   { body: '{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location \'chinaeast\' and API version \'2016-03-30\' for type \'virtualMachines\'. The supported api-versions are \'2015-05-01-preview, 2015-06-15\'. The supported locations are \'chinanorth, chinaeast\'."}}',
     headers:
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': '7aa6c6fb-c92d-452f-92c4-e60ce4d8fe23',
        'x-ms-correlation-request-id': '7aa6c6fb-c92d-452f-92c4-e60ce4d8fe23',
        'x-ms-routing-request-id': 'CHINAEAST:20160427T080430Z:7aa6c6fb-c92d-452f-92c4-e60ce4d8fe23',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Wed, 27 Apr 2016 08:04:30 GMT',
        connection: 'close',
        'content-length': '296' },
     statusCode: 400 },
  code: 'NoRegisteredProviderFound',
  body:
   { code: 'NoRegisteredProviderFound',
     message: 'No registered resource provider found for location \'chinaeast\' and API version \'2016-03-30\' for type \'virtualMachines\'. The supported api-versions are \'2015-05-01-preview, 2015-06-15\'. The supported locations are \'chinanorth, chinaeast\'.' },
  __frame:
   { name: 'createOrUpdateVM__14',
     line: 180,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine.js',
     prev:
      { name: 'createVM__1',
        line: 57,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js',
        prev: [Object],
        calls: 3,
        active: false,
        offset: 119,
        col: 19 },
     calls: 0,
     active: false,
     offset: 18,
     col: 81 },
  rawStack: [Getter] }
Error: No registered resource provider found for location 'chinaeast' and API version '2016-03-30' for type 'virtualMachines'. The supported api-versions are '2015-05-01-preview, 2015-06-15'. The supported locations are 'chinanorth, chinaeast'.
  <<< async stack >>>
  at createOrUpdateVM__14 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine.js:198:82)
  at createVM__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js:176:20)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vm.js:137:16)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/node_modules/azure-arm-compute/lib/operations/virtualMachines.js:909:19
    at retryCallback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest-azure/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/ms-rest-azure/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:539:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:516:9)
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:412:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest-azure/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
```

**Comment by amarzavery** [comment] 2016-04-27 16:35
@bingosummer - This is a known issue. I had brought this to Compute team's notice in a separate email internally.
@mahthi, @huangpf @sauryadas - Can you provide a timeline for `When will AzureChinaCloud support the current api-version "2016-03-30"?` This makes the latest version of CLI 0.9.20 useless for vm operations in ChinaCloud.

**Comment by bingosummer** [comment] 2016-04-29 00:21
Thanks @amarzavery for confirming it.
Another question: What's the latest version of CLI can support the old api-version "'2015-05-01-preview, 2015-06-15"?

**Comment by bingosummer** [comment] 2016-04-29 09:26
From my test, 0.9.18 is the latest version to support the old api-version "'2015-05-01-preview, 2015-06-15". And 0.9.19 and 0.9.20 both breaks the vm operations in ChinaCloud.

**Comment by huangpf** [comment] 2016-05-04 03:42
@bingosummer What's the API availability agreement/contract between Azure CLI releases in PROD and AzureChinaCloud releases?

@amarzavery Do we have the requirement that users can always use the public CLI releases immediately for AzureChinaCloud environment?

In my opinion, CLI team shall maintain releases or tags on releases for each national clouds. So, I don't think it's an ```IAAS``` ```P1``` bug, but it's more like a ```Team``` decision we have to discuss and make.

**Comment by bingosummer** [comment] 2016-05-04 14:26
@huangpf Sorry, I don't follow you with your questions. Could you explain more?

**Comment by amarzavery** [comment] 2016-05-04 17:06
@huangpf - AFAIK, Azure Production and AzureChina are pretty much on the same cadence. It will be bummer if customers cannot use the latest version of CLI to create a vm in AzureChina. 

This becomes more problematic, "if a bug was fixed in a command in 0.9.19, customer upgrades to that version and finds out that 0.9.19 targets a new api-version which is not deployed in his environment".

What is the timeline to deploy the latest api-version for compute in AzureChina?

**Comment by huangpf** [comment] 2016-05-04 17:51
@amarzavery Your assumption "retty much on the same cadence" is by-design-ly inaccurate. First of all, if Azure & AzureChina environments are the same, we won't have the sync-up issue here. Secondly, service roll-out takes time and order, and the same problem applies to other national clouds and geo-based environments, i.e. Canada & India regions, etc. 

So, I don't think (at least for now) it should be a requirement on CLI that: the commands have to be ready across all regions & clouds for the release.

The question can be translated into the following that has almost nothing to do with CLI (or PS/SDK): when will AzureChina, or any other regions/clouds, have the APIs & settings the same as latest Azure PROD.

I think the resolution is: 1) there is no guarantee that the latest CLI will work with all cloud environments; 2) figure out a way to determine which client tool can be used by which cloud, like the following matrix that describes API availability across regions: https://azure.microsoft.com/en-us/regions/#services

**Comment by eduardkoller** [comment] 2016-05-09 18:12
@bingosummer - This is caused by the fact that the API version of Azure China is older than the API version of Azure global. The workaround here is to use the previous version (0.9.18) of the released CLI: https://github.com/Azure/azure-xplat-cli/releases/tag/v0.9.18-hotfix

**Comment by huangpf** [comment] 2016-05-09 19:16
@eduardkoller 
How do we handle similar requests about CLI versions for various environments and national clouds onwards?

**Comment by bingosummer** [comment] 2016-06-14 06:27
@sauryadas 

Any update on this issue? Thanks.

cc: @amarzavery @huangpf @eduardkoller

**Comment by huangpf** [comment] 2016-06-18 06:05
+ @waynekuo as it's related to build-out.

**Comment by huangpf** [comment] 2016-06-20 05:40
@bingosummer 
According to the service team, the update was done last week. Could you please help check it again?  Thanks.

**Comment by huangpf** [comment] 2016-06-20 13:44
Please feel free to reopen if it's not resolved yet.

**Closed by huangpf** 2016-06-20 13:44 UTC
Labels: ARM, IAAS, P1, ServiceIssue, Team

**Comment by bingosummer** [comment] 2016-06-21 05:53
`0.10.1` works.
