### ISSUE TITLE
CLI: command parser do not parse correclty parameters with whitespaces in specified value

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2850] opened 2016-05-04 08:42 UTC
CLI Version: **0.9.20**
OS Type: at least Win (other OS not checked)
Installation via:  any 

Mode: **any**

Description:
`azure foo --bar "baz hello world"` will fail with parse expection:

error: unknown option `-xxx' 

Steps to reproduce:
1) ASM: Create Vnet with whitespace in it's name via old Portal; 
2) Then run `azure vm create --virtual-network-name "Vnet with whitespaces"`
3) Also reported issue here https://github.com/Azure/azure-xplat-cli/issues/2509

Error:
error: unknown option `--virtual-network-name'

Note: looks like this issue comes from `commander.js`, probably commander package needs to be updated

**Comment by MikhailTryakhov** [comment] 2016-05-05 09:04
There is no such error. The problem in related issue was in double quotas enetering.
Such steps will not reproduce specified error. Please close

**Comment by MikhailTryakhov** [comment] 2016-05-06 08:43
@huangpf @romangromov  @sauryadas can you *really* reproduce such issue?
I assume it must be closed as non-reproducable

**Comment by politician** [comment] 2016-05-09 20:41
@MikhailTryakhov Please let us know when you've actually run the following commands, and not just assumed that you know what will happen when you do.

1. Open a Bash prompt on a Linux/OSX box.
2. Run `azure vm create --virtual-network-name "\"Group Foo foo-vn\""` and let us know what you find.
3. Run `azure vm create --virtual-network-name "Group Foo foo-vn"` and let us know what you find.
4. Send us a screenshot of a new virtual network created with either of these command lines.

Cheers.

**Comment by MikhailTryakhov** [comment] 2016-05-10 11:32
Hi @politician 
usually we're sharing screenshots when we show that bug *exists*, not that all works fine :)

But to save some time I've reproduced all cases you wished.
1) Created vnet with whitespaces in name
![Created vnet with whitespaces in name](http://img.prntscr.com/img?url=http://i.imgur.com/66wkwPF.png)

2) Have a error creating vnet with your wrong example 2)
![error creating vnet](http://img.prntscr.com/img?url=http://i.imgur.com/z2xJpLL.png)

3) Successfully created vm related to this vnet with example 3) as I recommended before
![successfully created](http://img.prntscr.com/img?url=http://i.imgur.com/z2xJpLL.png)

4) Created vm is shown correctly
![details](http://img.prntscr.com/img?url=http://i.imgur.com/cPW7Vti.png)

@romangromov can you please share your screenshot which were the reason to open this issue.

@politician can you please provide details of your environment, steps and screenshots how to reproduce such issue.

**Comment by politician** [comment] 2016-05-12 01:27
As mentioned in #2509, we're talking about virtual networks and we're not talking about virtual machines.  I'd prefer to continue the discussion in one, but not both, of these threads moving forward.  Otherwise, we're just wasting time.  Nevertheless, here you go.

Environment: Azure Tools Version 0.9.15 running on Bash on Linux
Steps to reproduce / Screenshot:

<img width="712" alt="azure-vnet-create-bug" src="https://cloud.githubusercontent.com/assets/1149663/15201463/0a8a44ae-17a6-11e6-84ad-04fade45a467.png">

**Comment by politician** [comment] 2016-05-12 01:35
I will need to provide a screenshot of what happens when I perform a `vm create`, but I'll have to rollback my hotfix to do so, so it was easier to just show a `vnet create`.  I believe this is an example of the wider impact of this bug that @romangromov discovered.

**Comment by politician** [comment] 2016-05-12 02:29
> But to save some time I've reproduced all cases you wished.
> Can you please provide details of your environment, steps and screenshots how to reproduce such issue.

Thanks, it looks like it's working on your build, and that I've completely wasted my time here.  I'm unsubscribing from this issue.  Have a great day.

**Closed** 2016-05-12 03:00 UTC
Labels: Team
