### ISSUE TITLE
ASM: can't use commands after successful login

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2318] opened 2015-11-23 08:22 UTC
1) Run any command in ASM, getting error: `We don't have a valid access token`:
```
azure network application-gateway show test-app-gateway
info:    Executing command network application-gateway show
+ Looking up an Application Gateway "test-app-gateway"
error:   We don't have a valid access token. Please run "azure login" again.
info:    Error information has been recorded to C:\Users\roman.gromov\.azure\azure.err
error:   network application-gateway show command failed
```

2) Ok, lets run `azure login`:
```
azure-xplat-cli-ms>azure login
info:    Executing command login
|info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code C6P7J9YA6 to authenticate. If you're signing in as an Azure AD application, use the --username and --password parameter
s.
-info:    Added subscription EduardK - IaaS Tools
+
info:    login command OK

```

3) Again, run any command in ASM:
```
azure network application-gateway show test-app-gateway
info:    Executing command network application-gateway show
+ Looking up an Application Gateway "test-app-gateway"
error:   We don't have a valid access token. Please run "azure login" again.
info:    Error information has been recorded to C:\Users\roman.gromov\.azure\azure.err
error:   network application-gateway show command failed

```

**Comment by yugangw-msft** [comment] 2015-11-30 18:41
@romangromov , could you run "account list" to see whether you have multiple accounts. if yes, is the the account, you logged in, the active one?

**Comment by romangromov** [comment] 2015-12-02 08:01
@yugangw-msft well, now getting another error:

```
azure network vnet create MyNetwork --location "West US"
info:    Executing command network vnet create
info:    Using default address space start IP: 10.0.0.0
info:    Using default address space cidr: 8
info:    Using default subnet start IP: 10.0.0.0
info:    Using default subnet cidr: 11
+ Looking up network configuration
+ Looking up locations
+ Setting network configuration
error:   The subscription is in a disabled state.
```

**Comment by yugangw-msft** [comment] 2015-12-02 17:17
@romangromov, your subscription is disabled. Could you log in the portal and see what is the detail causes, say spending limit was reached, etc. FYI, "azure account list" should also have a field telling you the subscription status.

**Comment by yugangw-msft** [comment] 2015-12-03 03:48
I also made one more commit through #2345 in case your original error was caused by you fetched recent changes from the dev branch. anyway, give it and try and ping me if you see any new issue.
At the same time, I am closing this issue, but feel free to reopen it.

**Closed by yugangw-msft** 2015-12-03 03:48 UTC
