### ISSUE TITLE
deploying templates from azure-quickstart-templates broken

### ISSUE THREAD

**Issue by johngossman** [Azure/azure-xplat-cli#1821] opened 2015-06-05 02:43 UTC
D:\Projects\azure-quickstart-templates\101-simple-linux-vm>azure group create "jgtesttemp3" "West US" -f azuredeploy.json -d "testDeploy" -e azuredeploy.parameters.json
info:    Executing command group create
+ Getting resource group jgtesttemp3
+ Creating resource group jgtesttemp3
info:    Created resource group jgtesttemp3
+ Initializing template configurations and parameters
+ Creating a deployment
error:   The request content was invalid and could not be deserialized: 'Required property 'properties' not found in JSON. Path '', line 1, position 2.'.
info:    Error information has been recorded to C:\Users\John\.azure\azure.err
error:   group create command failed

**Comment by yugangw-msft** [comment] 2015-06-05 14:41
#1820 is the fix

**Comment by sedouard** [comment] 2015-06-05 16:24
dupe of https://github.com/Azure/azure-sdk-for-node/issues/1431#issuecomment-109323968

**Comment by yugangw-msft** [comment] 2015-06-11 16:37
the fix has been published as "azure-cli@0.9.4"

**Closed by yugangw-msft** 2015-06-11 16:37 UTC
Labels: ResourceManager
