### ISSUE TITLE
(node) warning: Recursive process.nextTick detected

### ISSUE THREAD

**Issue by didlich** [Azure/azure-xplat-cli#1564] opened 2015-02-05 12:40 UTC
I am using node v0.10.33, trying to upload a 29.75MB to blob storage:

`azure storage blob upload -a ...`

I get this warning, which leads to abort the upload

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
error:   Maximum call stack size exceeded
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded
```

**Comment by yaxia** [comment] 2015-05-18 05:11
Hi @didlich, thanks for reporting it. But I am not able to reproduce this issue. Is it constantly reproduced? Could you please provide more details?

**Comment by howie** [comment] 2015-10-27 04:08
Hi yaxia

We also have this problem.
You can  reproduced by open two terminal and run  azure storage blob upload simultaneous .

**Comment by amarzavery** [comment] 2016-07-15 01:37
@yaxia - Any update on this? Was this issue repro'd in the way suggested by @howie ?

**Comment by yaxia** [comment] 2016-07-15 01:50
+@hasonmsft to take a look

**Comment by hasonmsft** [comment] 2016-07-15 02:35
Still no luck for the repo. @howie , @didlich, can this issue still be reproduced from your side?

**Comment by didlich** [comment] 2016-07-15 08:55
@hasonmsft, after nodejs and azure-cli update I didn't try it any more

**Comment by hasonmsft** [comment] 2016-07-17 03:28
@didlich , thanks for information. Since we cannot repro this issue from our side, we'll close this issue for now. Feel free to re-open it if you get this issue in the future again.

**Closed by hasonmsft** 2016-07-17 03:28 UTC
Labels: Storage
