### ISSUE TITLE
azure vm quick-create asks for password even when ssh key file is provided.

### ISSUE THREAD

**Issue by sivaedupuganti** [Azure/azure-xplat-cli#2754] opened 2016-04-13 19:45 UTC
CLI Version: **0.9.19**
OS Type: Linux Ubuntu
Installation via:  npm

Mode: ARM

Description:
azure vm quick-create asks for password even when ssh key file is provided.

Steps to reproduce:
1) Run 
`azure vm quick-create -g arm-test -n vm0 -l centralus -y Linux -Q Canonical:UbuntuServer:15.10:15.10.201602220 -z Standard_D4 --ssh-publickey-file ~/.ssh/id_rsa.pub -u <username>`
It shouldn't prompt for password as I provided the ssh key file. 

It currently does,
```
info:    Executing command vm quick-create
Password: ***********
Confirm password: ***********
```

**Comment by amarzavery** [comment] 2016-04-13 20:12
@huangpf - Do take a look at this issue, when you get time

**Comment by huangpf** [comment] 2016-04-14 16:53
ok

**Comment by ahmetalpbalkan** [comment] 2016-04-20 21:42
this is clearly a regression. I remember this worked without prompting for password in earlier versions (which makes me think, it doesn't have proper tests). It's broken in 0.9.19 and 0.9.20.

@amarzavery has this made it to a release yet?

**Comment by amarzavery** [comment] 2016-04-20 21:52
@ahmetalpbalkan The fix is a part of release-0.9.20. The scenario reported in the original description above (where the command was prompting for password even when the ssh public key file is provided) does not happen. I just verified it again on my local box.

**Comment by ahmetalpbalkan** [comment] 2016-04-20 21:58
@amarzavery ah okay, fair point I realized I hit the npm upgrade path issue and stayed on 0.9.19... It works for me as well. We can close the issue.

**Comment by amarzavery** [comment] 2016-04-20 21:59
Cool thanks.

**Closed by amarzavery** 2016-04-20 21:59 UTC
Labels: ARM, IAAS
