### ISSUE TITLE
ASM: Add support to set NIC(s) for VM

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1785] opened 2015-05-17 06:42 UTC
Currently PS supports adding multiple NIC to VM http://azure.microsoft.com/blog/2014/10/30/multiple-vm-nics-and-network-virtual-appliances-in-azure/

We need to enable same feature in CLI

**Comment by anuchandy** [comment] 2015-05-18 18:07
The NIC needs to be attached to the VM during creation time. 

Once attached, you cannot modify. delete or add to the network interface collection of VM Role. 

So instead of having 'nic' command sub category under network, 'vm create' command needs to be updated to support passing nic configuration.

**Comment by anuchandy** [comment] 2015-05-18 18:49
Addressed this feature request in this PR https://github.com/MSOpenTech/azure-xplat-cli/pull/181
& available at https://github.com/MSOpenTech/azure-xplat-cli/tree/dev
Will close this issue once merged to upstream.

cc @kmouss

**Comment by HimanshuBri** [comment] 2015-05-19 07:21
@anuchandy getting following error while  adding multiple NIC to VM
<pre>
<code>
C:\May\19May\azure-xplat-cli-dev>node bin/azure vm create TestVm19M VMImage11 -l "West US" testuser pPa$$word@123 --virtual-network-name testvnet19m --subnet-names Su
bnet-1,Subnet-2 --nic-config nic1:Subnet-1:::,nic2:Subnet-2:::
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
+ Looking up image VMImage11
+ Looking up virtual network
+ Looking up cloud service
info:    cloud service TestVm19M not found.
+ Creating cloud service
+ Creating VM
+ Deleting cloud service
error:   Roles with secondary network interfaces can only be part of ONE subnet.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   vm create command failed


</code>
</pre>

**Comment by babumuralidharan** [comment] 2015-05-19 18:46
@HimanshuBri can you give some meaningful nic names and give a verbose output of the command run here ?

**Comment by anuchandy** [comment] 2015-05-20 05:05
@babumuralidharan as we discussed today changing to 'Ready For Test'

**Comment by HimanshuBri** [comment] 2015-05-20 06:50
@babumuralidharan  @anuchandy  Working fine now
<pre>
<code>
C:\May\20May\azure-xplat-cli-dev>node bin/azure vm create XplatTesttVm VMImage11 -l "West US" testuser Pa$$word@123 --vm-size ExtraLarge --virtual-network-name XplatT
estVnet --subnet-names Subnet-1 --nic-config "NetworkInterface1:Subnet-1::XplatTestNsg:Disabled","NetworkInterface2:Subnet-2::XplatTestNsg2:Disabled"
info:    Executing command vm create
+ Looking up image VMImage11
+ Looking up virtual network
+ Looking up cloud service
info:    cloud service XplatTesttVm not found.
+ Creating cloud service
+ Creating VM
info:    vm create command OK
</code>
</pre>

**Comment by babumuralidharan** [comment] 2015-06-09 18:00
Added as part of sprint49. Closing this issue.

**Closed by babumuralidharan** 2015-06-09 18:00 UTC
Labels: ASM, IAAS, Networking, P1, Ready For Test

**Comment by Kahelek** [comment] 2015-07-12 18:22
I am running on Windows.  I am a fairly experienced Level III Tech Support guy (mostly networking), but this is my first time using the node.js on Azure (changing focus) .. 

I'm not sure if xplat-cli is a derivative, or offshoot, of the stock azure cli that installs with npm install.  I tried running azure-xplay-cli install --g and that didn't help.  Now I tried to clone using git Desktop clone and this doesn't seem to be working either.

**Comment by Kahelek** [comment] 2015-07-12 18:29
I think my problem is that azure-xplat-cli is not installed with the Windows version, although it seems logical that would be available per the MSI file to install at https://github.com/MSOpenTech/azure-xplat-cli/tree/dev 

The problem is, even using that MSI file on that link,  azure-xplat-cli is not installed anywhere that you can find on your system, afterward.  

 Directory of C:\Users\kahelek\AppData\Roaming\npm\node_modules

07/12/2015  12:39 PM    <DIR>          .
07/12/2015  12:39 PM    <DIR>          ..
07/12/2015  12:39 PM    <DIR>          azure-cli
               0 File(s)              0 bytes
               3 Dir(s)  108,462,469,120 bytes free

so, it's not clear where I should clone this package and get the paths to align properly to test this out..

**Comment by Kahelek** [comment] 2015-07-12 19:09
Cloned this in Git desktop to node_modules, still not working.  

C:\Users\kahelek\AppData\Roaming\npm\node_modules\azure-xplat-cli [master]> azure vm create -z Large -l "South Central US" -n MyBrandNew-VM -w traffictrace -b "Frontend,Backend-2,Backend-3" -s "16c05fab-1b55-48fa-bdaa-2101ea2bedf1" -f "port1:Frontend:10.0.1.10:traffictrace:Enabled,port2:Backend-2:10
.0.2.10:traffictrace:Enabled,port3:Backend-3:10.0.3.10:traffictrace:Enabled" traffictrace.cloudapp.net Forti-disk-image azureadmin Passwordyy123!!
info:    Executing command vm create
+ Looking up image Forti-disk-image
+ Looking up virtual network
+ Looking up cloud service
warn:    --location option will be ignored
+ Getting cloud service properties
+ Looking up deployment
+ Creating VM
error:   Roles with secondary network interfaces can only be part of ONE subnet.
info:    Error information has been recorded to C:\Users\kahelek\.azure\azure.err
error:   vm create command failed

C:\Users\kahelek\AppData\Roaming\npm\node_modules\azure-xplat-cli [master]>
