### ISSUE TITLE
Uploading dynamic VHD may result in corrupt footer

### ISSUE THREAD

**Issue by szarkos** [Azure/azure-xplat-cli#1600] opened 2015-02-24 02:36 UTC
In some cases the size of the dynamic VHDs are being miscalculated, resulting in a corrupt footer after uploading.  This causes VHDs uploaded using this method to fail to boot on DS-sized VMs.

    $ azure vm image create image-name image.vhd --os linux -u https://......
    info:    Executing command vm image create
    warn:    The total size of blocks 31124 Mb is different
    warn:      from declared VHD size 31122 Mb

Notice that the detected size is 2MB larger than what is declared in the footer.  I'm not sure why this is the case, perhaps a rounding error somewhere in vhdTools.js?

According to qemu, the declared value of 31122 Mb is correct (32633782272 / 1024 / 1024 = 31122):

    $ qemu-img info image.vhd
    image: image.vhd
    file format: vpc
    virtual size: 30G (32633782272 bytes)
    disk size: 548M

In any case, after uploading the result is that 2MB is appended to the final fixed VHD.

As per the vhd spec: size_of_vhd_in_the_footer + 512bytes = size of file.  In this case, after uploading the size_of_file – size_in_footer is 2MB (and not 512bytes).

**Comment by kmouss** [comment] 2015-02-24 22:10
Following with Stephen and Rohit to get a sample VHD with this issue. This seems to be specific to VHDs that are dynamic (Khalid following up)

**Comment by anuchandy** [comment] 2015-03-02 18:18
Did initial investigation. Issue is specific to dynamic VHD but not all dynamic VHD will be affected.  We could repro this issue with CoreOS Dynamic VHD. 

Here is more details:

Created a dynamic VHD (with Ubuntu 12.04) with max size 40 GB (42949672960 Bytes). The footer of this VHD includes size attribute which says ‘42949672960’. The max table entries in the header indicates there are maximum 20480 entries in the BAT. The size of the each block is 2 MB (2097152) so total block size is 40 GB(42949672960). This means in cause of this dynamic VHD – size calculated using number of BAT entries and size specified in the footer are same.

In cause of the CoreOS VHD -  When calculating the total size using BAT there is additional  2 MB (2097152) as compared to the size stored in the footer. CLI is giving warning in this case. 

We have to consider BAT as authoritative because BAT references the data blocks. Using the size from footer instead of size calculated from BAT may cause last BAT entry to point to a block which not true block size (as footer overlaps last 512 bytes of this block).

Fix should be updating the footer with the size calculated from BAT. Still to verify this fix.

**Comment by anuchandy** [comment] 2015-03-03 21:40
Current Status: Fix is ready and shared private build for testing.

**Comment by crawford** [comment] 2015-03-09 16:56
@anuchandy What tool was used to create the Ubuntu VHD? CoreOS uses `qemu-img convert -f raw in.bin -O vpc out.vhd`.

**Comment by tmm1** [comment] 2015-03-27 03:43
We ran into similar issues and are using the following command: `VBoxManage convertfromraw --format VHD image.raw image.vhd`

**Comment by kmouss** [comment] 2015-04-01 22:35
Fix done. testing in progress now. Targeting next sprint.

**Comment by tmm1** [comment] 2015-04-14 20:20
Is there an ETA for when this fix will be available? Is there a branch we can try before the release?

**Comment by thauburger** [comment] 2015-04-21 03:01
@kmouss update? Is this ready for testing?

**Comment by kmouss** [comment] 2015-04-21 03:32
it is available here: http://deployvmtestwestus.blob.core.windows.net/share/azure-sdk-tools-xplat.zip

**Comment by tmm1** [comment] 2015-04-29 04:49
@kmouss Could you please point me at the PR or patch that fixes this issue?

**Comment by thauburger** [comment] 2015-05-11 06:18
@tmm1 let's give this a shot early this week.

**Comment by kmouss** [comment] 2015-05-12 22:03
Fixed planned for next Azure CLI update.

**Comment by thauburger** [comment] 2015-05-12 22:54
Do we have a date for next rollout?

Sent from Outlook




On Tue, May 12, 2015 at 3:04 PM -0700, "Khalid" <notifications@github.com> wrote:












Closed #1600.

**Comment by devigned** [comment] 2015-05-12 23:29
I'm going to reopen this for a bit to see if @tmm1 or @thauburger or @szarkos can confirm the resolution.

**Comment by tmm1** [comment] 2015-05-13 00:13
Looks like the fix is here, but hasn't been merged yet? https://github.com/MSOpenTech/azure-xplat-cli/pull/145

Can you confirm that this is supposed to work for the following invocation? I can update my local copy and try it if so.

```
$ azure storage blob upload -q -t Page myfile.vhd vm-images myfile.vhd
```

**Comment by anuchandy** [comment] 2015-05-13 00:47
@tmm1 as @szarkos reported, the fix is applied to the command:

azure vm image create ..

Please use the branch https://github.com/MSOpenTech/azure-xplat-cli

AFAIK 'azure storage blob upload' cannot be used to upload VHDs which has mismatch between BAT entries derived size and size record in footer.  'azure storage blob upload'  is not aware of VHD format, its a command fpr plain uploading for page or block blobs.

**Comment by tmm1** [comment] 2015-05-13 01:08
Unfortunately "azure vm image create" does not work when you try to upload
to a premium storage account.

Also "azure storage blob upload" is 2-3x faster at uploading.

**Comment by anuchandy** [comment] 2015-05-13 01:46
@tmm1 Thank you for validating.

This fix is not for premium storage. We have another work item for supporting premium storage, where we will be switch to new storage client used by 'azure storage blob upload'. 

As @szarkos reported this is a fix for error in footer calculation, would you mind validating this if possible?

We should see better uploading speed after switching to new storage client. Anyway speed will be still less for 'vm image create' as this command do md5 calculation and vhd verification.

**Comment by thauburger** [comment] 2015-05-13 19:50
@tmm1 @anuchandy

Premium storage wouldn't be an immediate blocker for us, as publishing needs to happen from a classic storage account at the moment.

**Comment by tmm1** [comment] 2015-05-13 20:26
I have confirmed that the MSOpenTech/azure-xplat-cli@dev fork is able to upload a dynamic VHD and boot a DS-series VM from it.

Uploading a 3.9GB dynamic VHD via `vm image create` is couple minutes faster than uploading a 80GB fixed VHD via `storage blob upload`:

```
# vm image create
warn:    The total size of blocks 81922 Mb is different
warn:      from declared VHD size 81921 Mb
info:    VHD size : 80 GB
info:    Uploading 3923968.5 KB
Requested:100.0% Completed:100.0% Running:   0 Time: 4m18s Speed: 15243 KB/s


# storage blob upload
Percentage: 100.0% (80.00GB/80.00GB) Average Speed: 206.35MB/S Elapsed Time: 00:06:37 
```

**Comment by thauburger** [comment] 2015-05-13 20:28
Awesome!

**Comment by thauburger** [comment] 2015-05-13 21:03
@tmm1 @anuchandy but of course, would love to see the perf improvement moved to `vm image create`

**Comment by anuchandy** [comment] 2015-05-13 21:20
@tmm1 thanks much for verifying the footer fix.

To comment on @tmm1 note: "Uploading a 3.9GB dynamic VHD via vm image create is couple minutes faster than uploading a 80GB fixed VHD via storage blob upload" -> yes in case of dynamic VHD we skip zero blocks so it will be faster.

@thauburger as mentioned in the earlier comment we are working on moving 'image create' to use new storage library, once it is done we will be able to use premium as target storage. Please see work item here: https://github.com/Azure/azure-xplat-cli/issues/1715

@devigned, @kmouss The footer calculation error has been fixed & verified. Should we close this one now or after merging with upstream?

**Comment by devigned** [comment] 2015-05-13 21:36
Let's get it merged. This is an awesome fix!

**Comment by babumuralidharan** [comment] 2015-06-02 18:06
Bug fix part of release 0.9.3. Closing this issue.

**Closed by babumuralidharan** 2015-06-02 18:06 UTC
Labels: IAAS, P1, Ready For Test
