### ISSUE TITLE
azure vm create with Custom data fails with file size around 63 KB

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1599] opened 2015-02-24 01:01 UTC
vm create with custom data fails if file size is around 63 KB.

command issued is given below
***************************************

$ node bin/azure vm create hydtest1 "3a50f22b388a4ff7ab41029918570fa6__Windows-Server-2012-Essentials-20140327-enus" bamura "Abcd.1234#" -l "West US" -w "testnameforvnw" -z "Medium" -r -d "C:\XPlat\CD1.txt" -n "HydVM1"

![image](https://cloud.githubusercontent.com/assets/1501823/3278174/a6233a96-f3aa-11e3-8808-fdc368e5fea6.png)

Analysis from @orangemocha, 

``` 
This appears to be a service issue.
VirtualMachineOperations.beginCreatingDeployment() in computeManagementClient.js
is sending an https request, to which the server never responds.
```

**Comment by kmouss** [comment] 2015-05-12 22:05
Need to validate if it is working with ARM. This is a server side issue in RDFE.

**Comment by sauryadas** [comment] 2016-05-03 18:23
@mahthi Can you please take a look at this?

**Comment by amarzavery** [comment] 2016-07-16 02:51
@sauryadas @huangpf - Any updates on this issue?

**Comment by amarzavery** [comment] 2016-07-16 02:51
If this issue is not going to be resolved then feel free to close it.

**Comment by huangpf** [comment] 2016-07-16 04:55
Yes, this is by design that there is a fairly small size limit for this.

**Closed by huangpf** 2016-07-16 04:55 UTC
Labels: IAAS, P3, ServiceIssue
