### ISSUE TITLE
azure login --service-principal with certificate doesn't work

### ISSUE THREAD

**Issue by mhr3** [Azure/azure-xplat-cli#3035] opened 2016-07-25 11:37 UTC
CLI Version: 0.10.2
OS Type: Mac
Installation via:  npm

Mode: ARM

Environment: AzureCloud

Description:
`azure login --service-principal --tenant [tenant] --certificate-file [pem] --thumbprint [thumbprint]` can't authenticate returning this error:

```
error:   Unable to acquire token due to error: Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS50027: Invalid JWT token. AADSTS90014: The required field 'iss' is missing.\r\nTrace ID: [...]\r\nCorrelation ID: [...]\r\nTimestamp: 2016-07-25 11:29:30Z","error_codes":[50027,90014],"timestamp":"2016-07-25 11:29:30Z","trace_id":"[...]","correlation_id":"[...]"}
```

Steps to reproduce:
1) Run `azure login --service-principal ...`

If I hardcode the service principal's Application ID into `AuthenticationContext.prototype.acquireTokenWithClientCertificate` in `adal-node/lib/authentication-context.js` and pass it as clientId for `new TokenRequest(...)`, the login is successful, but the token doesn't get saved properly in keychain and any further calls fail.

**Comment by amarzavery** [comment] 2016-08-03 01:16
@mhr3 - You can `export AZURE_USE_FILE_TOKEN_STORAGE=1` and this will use a file in the .azure directory in your home profile and will not use keychain, will solve one of your issues.

**Comment by haocs** [comment] 2016-08-10 20:38
@mhr3 , `-u --username` is required to login with service principal.  Please try login with -u option to see if the issue is solved. In the meanwhile, we will add validation functions for required options.

**Comment by haocs** [comment] 2016-08-11 21:51
https://github.com/Azure/azure-xplat-cli/pull/3090

**Comment by haocs** [comment] 2016-08-16 18:40
@mhr3 PR merged that adds required arguments validation. Please reopen this issue if needed.

**Closed by haocs** 2016-08-16 18:40 UTC
Labels: Team
