### ISSUE TITLE
ASM: vm image create command failed when VHD isn't a whole number (in MBs)

### ISSUE THREAD

**Issue by kmouss** [Azure/azure-xplat-cli#1784] opened 2015-05-16 02:07 UTC
# azure vm image create CentOS6 ./linux.vhd -o linux -l "North Europe"
info:    Executing command vm image create
+ Retrieving storage accounts
warn:    The total size of blocks 20482 Mb is different
warn:      from declared VHD size 20480.4140625 Mb
info:    VHD size : 20 GB
info:    Uploading 2039808.5 KB
Requested:100.0% Completed:100.0% Running:   0 Time: 4m 3s Speed:  8398 KB/s
info:    https://portalvhdsh8xx858f63663.blob.core.windows.net/vm-images/linux.vhd was uploaded successfully
error:   The VHD https://portalvhdsh8xx858f63663.blob.core.windows.net/vm-images/linux.vhd has an unsupported virtual size of 21475270656 bytes.  The size must be a whole number (in MBs).
info:    Error information has been recorded to /var/root/.azure/azure.err
error:   vm image create command failed

Apparently Azure requires very specific image sizes and common image conversion tools do not.

**Comment by anuchandy** [comment] 2015-05-16 05:36
@kmouss Have you tried using the CLI with the patch applied for footer calculation ? https://github.com/msopentech/azure-xplat-cli/tree/dev

Hope this is not premium storage account as we know CLI has issue with Premium stg.

**Comment by anuchandy** [comment] 2015-05-16 05:50
Ok, Seems this is a known limitation for both PowerShell and CLI. Please see this post http://azure.microsoft.com/blog/2014/05/22/running-freebsd-in-azure/ from Stephen Zarkos. 

As per this blog the suggested fix is to: simply resize the VHD to ensure the disk is an even MB before uploading

**Comment by babumuralidharan** [comment] 2015-06-09 18:08
Closing this issue as we have sufficient background and in case the  publisher needs to ensure VHD size in even before trying to use image and create VM.

**Closed by babumuralidharan** 2015-06-09 18:08 UTC
Labels: IAAS, P1, Ready For Test

**Comment by jcollie** [comment] 2015-06-15 16:11
There's something wrong with the instructions provided in http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-create-upload-vhd-generic/

I followed the instructions as closely as I could, and I still get the error:

    $ wget http://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-22-20150521.x86_64.raw.xz
    --2015-06-15 11:00:28--  http://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-22-20150521.x86_64.raw.xz
    Resolving download.fedoraproject.org (download.fedoraproject.org)... 2610:28:3090:3001:dead:beef:cafe:fed3, 2604:1580:fe00:0:5054:ff:feae:702c, 2607:f188::dead:beef:cafe:fed1, ...
    Connecting to download.fedoraproject.org (download.fedoraproject.org)|2610:28:3090:3001:dead:beef:cafe:fed3|:80... connected.
    HTTP request sent, awaiting response... 302 Found
    Location: http://mirror.cc.columbia.edu/pub/linux/fedora/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-22-20150521.x86_64.raw.xz [following]
    --2015-06-15 11:00:30--  http://mirror.cc.columbia.edu/pub/linux/fedora/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-22-20150521.x86_64.raw.xz
    Resolving mirror.cc.columbia.edu (mirror.cc.columbia.edu)... 128.59.59.71
    Connecting to mirror.cc.columbia.edu (mirror.cc.columbia.edu)|128.59.59.71|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 153464172 (146M) [application/x-xz]
    Saving to: ‘Fedora-Cloud-Base-22-20150521.x86_64.raw.xz’
    
    Fedora-Cloud-Base-22-20150521.x86_64 100%[======================================================================>] 146.35M  5.85MB/s   in 38s    
    
    2015-06-15 11:01:08 (3.86 MB/s) - ‘Fedora-Cloud-Base-22-20150521.x86_64.raw.xz’ saved [153464172/153464172]
    
    $ unxz Fedora-Cloud-Base-22-20150521.x86_64.raw.xz 
    $ ls -l
    total 529044
    -rw-rw-r--. 1 jcollie jcollie        327 Jun 15 11:01 c.sh
    -rw-rw-r--. 1 jcollie jcollie 3221225472 May 21 19:13 Fedora-Cloud-Base-22-20150521.x86_64.raw
    $ cat c.sh
    rawdisk="Fedora-Cloud-Base-22-20150521.x86_64.raw"
    vhddisk="Fedora-Cloud-Base-22-20150521.x86_64.vhd"
    
    MB=$((1024*1024))
    size=$(qemu-img info -f raw --output json "$rawdisk" | \
           gawk 'match($0, /"virtual-size": ([0-9]+),/, val) {print val[1]}')
    
    rounded_size=$((($size/$MB + 1)*$MB))
    echo "Rounded Size = $rounded_size"
    $ sh c.sh
    Rounded Size = 3222274048
    $ qemu-img resize -f raw Fedora-Cloud-Base-22-20150521.x86_64.raw 3222274048
    Image resized.
    $ ls -l
    total 529044
    -rw-rw-r--. 1 jcollie jcollie        327 Jun 15 11:01 c.sh
    -rw-rw-r--. 1 jcollie jcollie 3222274048 Jun 15 11:02 Fedora-Cloud-Base-22-20150521.x86_64.raw
    $ qemu-img convert -f raw -o subformat=fixed -O vpc Fedora-Cloud-Base-22-20150521.x86_64.raw Fedora-Cloud-Base-22-20150521.x86_64.vhd
    $ ls -l
    total 1057108
    -rw-rw-r--. 1 jcollie jcollie        327 Jun 15 11:01 c.sh
    -rw-rw-r--. 1 jcollie jcollie 3222274048 Jun 15 11:02 Fedora-Cloud-Base-22-20150521.x86_64.raw
    -rw-r--r--. 1 jcollie jcollie 3222503936 Jun 15 11:02 Fedora-Cloud-Base-22-20150521.x86_64.vhd
    $ azure vm image create --location "Central US" --os Linux Fedora-Cloud-Base-22-20150521.x8664 Fedora-Cloud-Base-22-20150521.x86_64.vhd
    info:    Executing command vm image create
    + Retrieving storage accounts                                                  
    info:    VHD size : 3073 MB
    info:    Uploading 3146976.5 KB
    Requested:100.0% Completed:100.0% Running:   0 Time:   47s Speed: 13966 KB/s 
    info:    https://dmacclinux01.blob.core.windows.net/vm-images/Fedora-Cloud-Base-22-20150521.x86_64.vhd was uploaded successfully
    error:   The VHD https://dmacclinux01.blob.core.windows.net/vm-images/Fedora-Cloud-Base-22-20150521.x86_64.vhd has an unsupported virtual size of 3222503424 bytes.  The size must be a whole number (in MBs).
    info:    Error information has been recorded to /home/jcollie/.azure/azure.err
    error:   vm image create command failed

**Comment by szarkos** [comment] 2015-08-28 21:54
@jcollie, sorry for responding so late.  Can you please tell me what distribution you are using, and also the version of qemu-img and CLI tools you have?  I would like to narrow down this issue.

I tried to repro using the same Fedora image you tested above, however I could not reproduce the issue.  The resize worked as expected and I was able to create an image from the resulting VHD.  In my case I tested using an Ubuntu 14.04 VM, with qemu-img version 2.0.0 and xplat CLI v0.9.8.  Interestingly enough, this Fedora .raw image is already aligned to 1MB, so a resize isn't even required here :)  But in any case resizing +1MB should not cause the issue you're seeing.

Thanks,
Steve

**Comment by chris-milsted** [comment] 2016-03-25 08:27
see here:

https://bugs.launchpad.net/qemu/+bug/1490611

**Comment by anjalinn** [comment] 2017-03-05 01:22
I am seeing same issue, for linux image:

 I want to upload a Linux image (which is qcow2) after converting to VHD image, to Azure.

I converted the qcow2 image to raw:

qemu-img convert -f qcow2 -O raw myimage.qcow2 myimage.img

Next, my raw image is an exact multiple of 1M, so I don't need to resize it.

ls -l myimage.img

-rw-r--r-- 1 user1 user11 2313158656 Mar 5 00:18 myimage.img

<2313158656 is exact multiple of 1M>

Then I converted the raw to VHD on a Ubuntu VM which has qemu 2.6.1 installed, using the force option:

qemu-img convert -f raw -o subformat=fixed,force_size -O vpc myimage.img myimage.vhd

Now, the qemu-img seems to have added 512 bytes to the image, hence I still can't upload in Azure.

ls -l myimage.vhd

-rw-r--r-- 1 user1 user1 2313159168 Mar 5 00:39 myimage.vhd

Uploading this VM to azure gives this error:

'The VHD for disk 'clid01b1a17d9ec0eb1-os-1488675181694' with blob https://vmxstorage.blob.core.windows.net/vhddisks/vFPC-20170216.vhd has an unsupported virtual size of 2206.4765625 MB. The size must be a whole number in (MBs).'.

How I create a VM with the correct size of multiple of an MB? Can you please help?

**Comment by macrokernel** [comment] 2021-02-01 13:59
> qemu-img convert -f raw -o subformat=fixed,force_size -O vpc myimage.img myimage.vhd
> Now, the qemu-img seems to have added 512 bytes to the image, hence I still can't upload in Azure.

I am having the the same issue, qemu-img is adding 512 bytes to the VHD image. I also tried using VBoxManage, but it is adding 156160 bytes: 
VBoxManage convertfromraw --format VHD --variant Fixed image.img image.vhd

**Comment by joshspicer** [comment] 2021-04-06 16:06
I tried manually offsetting the raw image by 512 bytes (to try and compensate), but qemu-img _still_ is 512 bytes off of a MB boundary. 

![image](https://user-images.githubusercontent.com/23246594/113742295-7aa61200-96d0-11eb-8ccc-9f4961149fcd.png)
Using 5.2.0 qemu on Mac.
