### ISSUE TITLE
Login issue ARM mode.

### ISSUE THREAD

**Issue by pikumarmsft** [Azure/azure-xplat-cli#2011] opened 2015-08-11 09:18 UTC
Hi 
I am not able to login using ARM mode. 
I am getting following exception when I use azure login -u *********@microsoft.com

Tue Aug 11 2015 14:38:33 GMT+0530 (India Standard Time):
{ [Error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50079: Strong authentication enrollment (proof-up) is required.\r\nTrace ID: c19b083b-bcb1-4a14-8a6a-1c0edf402d3b\r\nCorrelation ID: 471ded25-3d2e-4edb-9d33-39c2cb2e5055\r\nTimestamp: 2015-08-11 09:08:32Z","error_codes":[50079],"timestamp":"2015-08-11 09:08:32Z","trace_id":"c19b083b-bcb1-4a14-8a6a-1c0edf402d3b","correlation_id":"471ded25-3d2e-4edb-9d33-39c2cb2e5055","submit_url":null,"context":null}]
  stack: [Getter/Setter],
  __frame: 
   { name: '__1',
     line: 42,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js',
     prev: undefined,
     calls: 2,
     active: false,
     offset: 48,
     col: 43 },
  rawStack: [Getter] }
Error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50079: Strong authentication enrollment (proof-up) is required.\r\nTrace ID: c19b083b-bcb1-4a14-8a6a-1c0edf402d3b\r\nCorrelation ID: 471ded25-3d2e-4edb-9d33-39c2cb2e5055\r\nTimestamp: 2015-08-11 09:08:32Z","error_codes":[50079],"timestamp":"2015-08-11 09:08:32Z","trace_id":"c19b083b-bcb1-4a14-8a6a-1c0edf402d3b","correlation_id":"471ded25-3d2e-4edb-9d33-39c2cb2e5055","submit_url":null,"context":null}
  <<< async stack >>>
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js:90:44)
  <<< raw stack >>>
    at Logger.createError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\log.js:196:13)
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\util.js:133:25)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:824:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by romangromov** [comment] 2015-08-11 12:41
@pikumarmsft please see https://github.com/Azure/azure-xplat-cli/issues/1935

**Comment by devigned** [comment] 2015-08-11 15:08
Closing as it's a duplicate of #1935. We are targeting 9/2 release to enable MFA.

**Closed by devigned** 2015-08-11 15:08 UTC
