### ISSUE TITLE
Cross-account `storage blob copy start` fails with authentication error

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2048] opened 2015-08-21 02:33 UTC
The following AzCopy command **works** when I copy a public blob from some storage account into my storage:

    > azcopy /Source:https://REDACTED.blob.core.windows.net/vhds /Dest:https://ahmetb.blob.core.windows.net/snappy-test/ /destkey:REDACTED /Pattern:snappy-20150818-os-2015-08-18.vhd

However the following command **fails**:

```sh
$ export AZURE_STORAGE_ACCOUNT=ahmetb
$  export AZURE_STORAGE_ACCESS_KEY="REDACTED"
$ azure storage blob copy start \
    --source-uri https://REDACTED.blob.core.windows.net/vhds/liz-snappy-20150818-os-2015-08-18.vhd snappy-test \
    --dest-container snappy-test 
error:   Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:76552f50-0001-00dc-17b9-db434e000000
Time:2015-08-21T02:31:18.3679934Z
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   storage blob copy start command failed
```

I verified with `echo $AZURE_STORAGE_ACCESS_KEY` that there are no problems with the string escaping etc. Looks like a bug to me.

**Comment by ahmetalpbalkan** [comment] 2015-08-31 20:25
Any acks/updates?

**Comment by yugangw-msft** [comment] 2015-08-31 20:50
@yaxia, could you please take a look

**Comment by yaxia** [comment] 2015-09-01 02:13
@ahmetalpbalkan , I cannot reproduce the issue at my side. Just share some findings from you command:
* The destination container name "snappy-test" was in both --soruce-uri and --dest-container. Though it won't impact as it will be override by the --dest-container option, let's try to remove it.
* In AzCopy, the source blob was snappy-20150818-os-2015-08-18.vhd while in xplat you were trying copy liz-snappy-20150818-os-2015-08-18.vhd. Is liz-snappy-20150818-os-2015-08-18.vhd publicly accessible? If it is not, you may need the blob sas embedded in the source URI.

If above doesn't work, could you run the command with -vv option and share me the verbose log? Thanks.

**Comment by ahmetalpbalkan** [comment] 2015-09-01 05:05
@yaxia In AzCopy that was the `/Pattern` so that was matching the blob name somehow. But the actual blob name is `liz-` so the xplat example is correct.  Also the blob is public.

Sending you email about the `-vv` output as it contains secrets.

**Comment by yaxia** [comment] 2015-09-24 07:17
As discussed in mail, there is no repro from my side. It may caused by the some codes were referring to old packages. We agree to close the issue.

**Comment by ahmetalpbalkan** [comment] 2015-09-24 07:18
Makes sense, turns out the bug was about the node streamline package removing artifacts from earlier versions after the npm upgrades.

**Closed** 2015-09-24 07:17 UTC
Labels: Storage
