### ISSUE TITLE
azure vm create --virtual-network-name doesn't support names with whitespace (with suggested code fix)

### ISSUE THREAD

**Issue by politician** [Azure/azure-xplat-cli#2509] opened 2016-02-05 07:53 UTC
The `--virtual-network-name` option doesn't support virtual network names with whitespace as are (now?) being generated by the new Azure Portal.  

```Bash
azure vm create --virtual-network-name "\"Group Foo foo-vn\""
```

If you don't escape the quotes, then the parser interprets the string as a VM image name, so you've got to escape the quotes.

Then, however, the comparison in `vmclient.js getNetworkInfo` fails due to string mismatch on the `virtualNetworkSites` list.

So, just add the following code to (at least) `vmclient.js createVM line 119`.

```JS
    if (options.virtualNetworkName) {
      options.virtualNetworkName = options.virtualNetworkName.replace(/\"/g, '');
    }
```

I don't care about your contributor CLA or whatever, so I won't be submitting a pull request.  Instead, I'm just hacking up my copy because I've got deadlines that are real, so feel free to take or leave this bug report.

**Comment by huangpf** [comment] 2016-02-05 19:27
@sauryadas Please help triage.

**Comment by sauryadas** [comment] 2016-02-11 22:03
@politician Are you sure you created a virtual network with white spaces in the new portal? I wasnt able to create one.

**Comment by sauryadas** [comment] 2016-02-22 06:59
@politician Please respond to this thread in 7 days otherwise i will need to close this thread as resolved.

**Comment by sauryadas** [comment] 2016-04-29 03:58
@politician Closing as i have not heard back from you

**Comment by politician** [comment] 2016-04-29 19:38
@sauryadas This is *not* an issue with the Portal.  The issue is with the `azure create` command when it's used in Bash.

**Did you try running the command I included in the issue?**

Steps to Reproduce:
1. Run the command `azure vm create --virtual-network-name "\"Group Foo foo-vn\""` in Bash
2. Observe that it does not work.
3. Apply the code fix above.
4. Rerun the command.
5. Observe that the virtual network is created successfully.

**Comment by sauryadas** [comment] 2016-04-29 20:24
@politician got it.. sorry about the confusion.

**Comment by huangpf** [comment] 2016-04-29 20:31
This is related to VNet feature that may be used differently by Portal and CLI. Add @romangromov to help confirm -- does ASM API support VNet resource name with spaces?

**Comment by romangromov** [comment] 2016-05-04 08:46
+ @MikhailTryakhov for the same.

Hi guys, checked a few things:
* it's possible to create a Vnet (or any kind of resource) with whitespaces in name via Azure **ASM** API (Note: it's not true for `ARM`);
* reported issue by @politician is applied to every cli command and not only to `vm create`, so I've started new issue here https://github.com/Azure/azure-xplat-cli/issues/2850
* proposed fix by @politician is workaround only for a single use case, I suggest do not apply this and `fix/wait for fix` for a common issue shared above.

Hope this helps

**Comment by MikhailTryakhov** [comment] 2016-05-05 08:22
Hi guys 
Thank you @romangromov for adding me.
As I can see, we *can* make Vnet names with whitespaces in ASM for sure. The problem is that @politician enters name with extra-quotas. 
We should enter 
```
azure vm create --virtual-network-name "Group Foo foo-vn"
```
entering ```"\"Group Foo foo-vn\"" ``` we have *"Group Foo foo-vn"* value (with quotas) for vnet. I think it's not the same value as *Group Foo foo-vn* and that's the reason of the problems.

Please let me know was my answer helpful

**Comment by MikhailTryakhov** [comment] 2016-05-06 08:37
@huangpf @amarzavery @sauryadas guys can you review comment above and close this issue?

**Comment by politician** [comment] 2016-05-09 20:33
@MikhailTryakhov Have you tried the command that you propose in Bash? It doesn't work.

**Comment by MikhailTryakhov** [comment] 2016-05-10 11:25
Hi @politician sure I've tested it in bash. Did you?
It worked correctly in my case without quotas.
![http://img.prntscr.com/img?url=http://i.imgur.com/3to3cI1.png]
@romangromov could you please share how did you reproduced such error?

**Comment by politician** [comment] 2016-05-12 01:18
Of course I tested it, otherwise I wouldn't have filed the original bug. :)

<img width="712" alt="azure-vnet-create-bug" src="https://cloud.githubusercontent.com/assets/1149663/15201324/b690f42a-17a4-11e6-8499-b37d545fe09f.png">

**Comment by politician** [comment] 2016-05-12 01:22
Oh, PS, we're talking about Virtual Networks, not VMs.

**Comment by politician** [comment] 2016-05-12 02:17
I'm unsubscribing from this issue.  From your screenshots, it's obviously working on whatever build you're currently using which is probably newer than the build I was using, so the issue must have been resolved in the interim.  Thanks for the screenshots.

**Closed** 2016-05-12 02:59 UTC
Labels: ASM, IAAS, Networking, P2
