### ISSUE TITLE
ARM : Creation of the Virtual machine fails as the command replaces the Storage account being used

### ISSUE THREAD

**Issue by k2velocity** [Azure/azure-xplat-cli#2853] opened 2016-05-04 17:03 UTC
CLI Version: 0.9.20
OS Type:  Win / Linux (Centos
Installation via:  npm / brew / win-or-mac installer / docker / github repo

Mode: ARM 
Description:
Creation of the Virtual machine fails as the command replaces the Storage account being used

$ azure vm create "Resourcegroupname" "Vmname" westus -y Linux -o "storageexample1" -d "https://storageexample1.blob.core.windows.net/vhds/Sample VM File.vhd" -z Standard_DS3 -N Nic1,Nic2,Nic3
info:    Executing command vm create
+ Looking up the VM "VMname"
info:    Using the VM Size "Standard_DS3"
+ Looking up the NIC "Nic1"
+ Looking up the NIC "Nic2"
+ Looking up the NIC "Nic3"
+ Looking up the storage account storageexample1
error:   clisto1411610431vt800-we is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.
info:    Error information has been recorded to /Users/user/.azure/azure.err
error:   vm create command failed

Update 👍 
===========

The VM creation works if boot Diagnostics is Skipped

azure vm create "Resourcegroupname" "Vmname" westus -y Linux -o "storageexample1" -R vhds -d "storageexample1.blob.core.windows.net/vhds/Sample VM File.vhd" -z Standard_DS3 -N Nic1,Nic2,Nic3 --disable-boot-diagnostics
info:    Executing command vm create
+ Looking up the VM "Vmname"
info:    Using the VM Size "Standard_DS3"
info:    The [OS, Data] Disk or image configuration requires storage account
+ Looking up the storage account "storageexample1"
+ Looking up the NIC "Nic1"
+ Looking up the NIC "Nic2"
+ Looking up the NIC "Nic3"
+ Creating VM "Vmname"
info:    vm create command OK

**Comment by amarzavery** [comment] 2016-05-04 17:08
@huangpf @sauryadas - One more.

**Comment by huangpf** [comment] 2016-05-04 18:01
Looks like a bug in the boot diagnostics storage account name generation part.

The mitigation is to 1) skip boot diagnostics, or 2) give a specific storage name/link input to it.

**Comment by k2velocity** [comment] 2016-05-04 19:28
Yes if i skip Boot diagnostics with  --disable-boot-diagnostics the VM gets created .

Do you have the Flags that i need to provide if i wanted to use a Specific Storage path/Link

**Comment by huangpf** [comment] 2016-05-04 20:38
Yes:
```
help:      --boot-diagnostics-storage-uri <boot-diagnostics-storage-uri>          
Optional. Specify storage account URL for boot diagnostics. 
In the format of 'https://your_stoage_account_name.blob.core.windows.net/'.
```

**Comment by eduardkoller** [comment] 2016-05-09 18:04
@k2velocity - does this workaround solve the problem?
@huangpf - when can we have a fix for the boot diagnostics storage account name generation?

**Comment by k2velocity** [comment] 2016-05-10 01:47
@eduardkoller :   Yes it does

The VM creation works if boot Diagnostics is Skipped

azure vm create "Resourcegroupname" "Vmname" westus -y Linux -o "storageexample1" -R vhds -d "storageexample1.blob.core.windows.net/vhds/Sample VM File.vhd" -z Standard_DS3 -N Nic1,Nic2,Nic3 --disable-boot-diagnostics
 info: Executing command vm create
•Looking up the VM "Vmname" info: Using the VM Size "Standard_DS3" info: The [OS, Data] Disk or image configuration requires storage account
•Looking up the storage account "storageexample1"
•Looking up the NIC "Nic1"
•Looking up the NIC "Nic2"
•Looking up the NIC "Nic3"
•Creating VM "Vmname" info: vm create command OK

**Comment by k2velocity** [comment] 2016-05-23 17:47
Any updates on this?

**Comment by taylorsmcclure** [comment] 2016-08-18 22:57
As people have mentioned this error is caused by lax sanitation for hyphens in VM names. This happens when the `vm create` command is not given `--disable-boot-diagnostics` or custom boot diagnostics parameters for log/metric storage. By default `vm create` will attempt to create a 'clisto' storage account for diagnostics logs.

As of Jul 6 the following pull request to sanitize '-' characters from vmName was merged with the master branch: https://github.com/Azure/azure-xplat-cli/commit/1f0714a6e02908bd8449b7d514223a07bb10f3f9

Solution to this issue: Update xplat CLI to latest version from master branch.

**Closed** 2016-08-18 23:02 UTC
Labels: ARM, IAAS
