### ISSUE TITLE
Error: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._]+$/

### ISSUE THREAD

**Issue by mcm-ham** [Azure/azure-xplat-cli#3032] opened 2016-07-22 07:12 UTC
CLI Version: 0.10.2
OS Type: Win
Installation via:  npm

Mode: ARM

Environment: AzureCloud

Description:
Resource group name can only contain 'w' and no other alphanumeric characters.

Steps to reproduce:
1) Run `azure group create 'test-group-name' 'East Asia'`

Error stack trace:

```
2016-07-22T07:09:01.227Z:
{ [Error: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._]+$/]
  stack: [Getter/Setter],
  __frame: 
   { name: '__1',
     line: 79,
     file: 'C:\\Users\\MichaelM\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\group\\group.js',
     prev: 
      { name: 'group_createResourceGroup__3',
        line: 72,
        file: 'C:\\Users\\MichaelM\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\lib\\commands\\arm\\group\\group.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 6,
        col: 20 },
     calls: 0,
     active: false,
     offset: 1,
     col: 35 },
  rawStack: [Getter] }
Error: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._]+$/
  <<< async stack >>>
    at ResourceGroups.get (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-arm-resource\lib\resource\operations\resourceGroups.js:749:15)
    at Object.getGroup (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\groupUtils.js:33:25)
    at __1 (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:80:29)
  at __1 (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:80:36)
  at group_createResourceGroup__3 (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:78:21)
  at __1 (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:55:32)
  <<< raw stack >>>
    at ResourceGroups.get (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-arm-resource\lib\resource\operations\resourceGroups.js:749:15)
    at Object.getGroup (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\groupUtils.js:33:25)
    at __$__1 (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:80:29)
    at __func (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:47:5)
    at Object.__1 (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:78:165)
    at Interactor.__.extend.withProgress (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\util\interaction.js:169:12)
    at __$group_createResourceGroup__3 (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:78:30)
    at __func (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:47:5)
    at AzureCli.group_createResourceGroup__3 [as createResourceGroup] (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:72:248)
    at __$__1 (C:\Users\MichaelM\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group.js:55:20)
```

**Comment by haocs** [comment] 2016-07-22 18:16
@mcm-ham, `test-group-name` is a valid name for resource group actually. I think the issue caused by single quotation marks in your command. Single quotations are considered as part of the resourceGroupName string. Please quote your command arguments with `"` to see if works.

**Comment by mcm-ham** [comment] 2016-07-25 02:39
Thanks using double quote instead of single quote worked. The regex is a bit confusing.

**Comment by amarzavery** [comment] 2016-07-25 18:01
closing this issue as this looks resolved.

**Closed by amarzavery** 2016-07-25 18:01 UTC

**Comment by mcm-ham** [comment] 2016-07-28 06:07
It's probably a good idea to update your guide from single quote to double quotes too. https://azure.microsoft.com/en-us/documentation/articles/key-vault-manage-with-cli/
