### ISSUE TITLE
Specifying subnet-id doesn't work when creating VM

### ISSUE THREAD

**Issue by braderhart** [Azure/azure-xplat-cli#2948] opened 2016-06-20 05:33 UTC
CLI Version: 0.10.1
OS Type: Linux (Ubuntu)
Installation via:  docker

Mode: ARM

Environment: AzureCloud

Description:
`azure vm create -S` subnet-id doesn't work. Still prompts for vnet name.

Steps to reproduce:
1) Run `azure vm create -S`

**Comment by sauryadas** [comment] 2016-06-23 06:12
@huangpf need to fix this as well...

**Comment by huangpf** [comment] 2016-06-23 07:54
I think it's by design to require vnet name. @braderhart What's your expected use case?

**Comment by braderhart** [comment] 2016-06-23 08:13
By specifying subnet-id it can use a subnet and vnet in another resource group. You can create a new NIC this way:

`azure network nic create -u` or `azure network nic create --subnet-id`

Therefore it should work the same with `azure vm create -S` or `azure vm create --subnet-id`. Otherwise it is an extra step to first create the NIC instead of having it created with the VM.

**Comment by Krylon360** [comment] 2016-07-12 17:38
I submitted #2940 about this last month. PR #3002 / #3007 which closes #2940 should fix the issue.

**Comment by MikhailTryakhov** [comment] 2016-07-12 17:51
Thanks @Krylon360 
The fix from [PR#3007](https://github.com/Azure/azure-xplat-cli/pull/3007) would be fixed in next release. 
Please let me know if you have any questions

**Closed by MikhailTryakhov** 2016-07-12 17:51 UTC
Labels: ARM, IAAS
