### ISSUE TITLE
ARM: `azure vm quick-create` with SSH key

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2135] opened 2015-09-24 20:40 UTC
I know we want to keep `vm quick-create` command simple but using passwords in Linux VM sort of bugs me every time. It's not a common practice. Maybe in the `<admin-password>` field can we do something like `<admin-password | @path-to-public-key>` that would allow users to pick an option?

**Comment by squillace** [comment] 2015-09-28 18:51
+1.

**Comment by squillace** [comment] 2015-11-02 22:52
@amarzavery @devigned Where are we on this? Current behavior is in fact highly non-standard and decidedly unsecure at the same time. But it's easier! :-)

**Comment by squillace** [comment] 2015-12-15 00:36
@amarzavery @devigned reping.

**Comment by devigned** [comment] 2015-12-15 11:40
@singhkay thoughts on this?

**Comment by singhkay** [comment] 2015-12-15 18:21
Adding @sauryadas who owns CLI

**Comment by squillace** [comment] 2015-12-15 19:14
@sauryadas OK, so what's the triage with respect to this issue?

**Comment by squillace** [comment] 2016-01-07 01:45
@sauryadas just repinging for the new year. :-) @madhana you were just in a meeting with us and Corey in which this specific bug came up. Can we fix or won't fix, yet?

**Comment by madhana** [comment] 2016-01-07 02:03
Sorry for the lack of response here. I think this is a valid ask. We will take a look at this in the next few days

**Comment by squillace** [comment] 2016-01-07 02:13
Coolio. Thanks.

**Comment by huangpf** [comment] 2016-01-07 19:38
@squillace I tend to agree that it's better for CLI user to use pub key/path for linux VMs. 

BTW, I think this item is a feature request, not a bug, for the quick-create command. So, assign to @sauryadas for now.

**Comment by squillace** [comment] 2016-01-07 20:18
@huangpf that sounds fine. Either "fixing it" or "adding that feature" is very, very important. :-)

**Comment by sauryadas** [comment] 2016-01-12 00:47
@squillace work item has been created. Should be available in the Feb CLI release

**Comment by squillace** [comment] 2016-01-12 00:54
Yay!

**Comment by huangpf** [comment] 2016-02-05 19:31
Fix in ```0.9.15```. Close for now.

**Closed by huangpf** 2016-02-05 19:31 UTC
Labels: ARM, IAAS

**Comment by squillace** [comment] 2016-02-05 21:57
<3
