### ISSUE TITLE
ARM: `azure vm create` keeps creating storage accounts

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1761] opened 2015-05-12 22:28 UTC
(Related: #1760 causes CLI to create a storage account for the VM disk before validating all `azure vm create`.)

So I keep running this  same `azure vm create [...]` with wrong parameters over and over again and  **it creates a new storage account** instead of previously used one. (ARM mode)

Not sure if bug or feature. @devigned 

Below you can see that it says "Could not find any storage accounts in the region "westus", trying to create new one" over and over again.

```
 ➜  ~  azure vm create "ahmet-rg" "ahmet-testvm" "westus" "Linux" --image-name "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB" -u azureuser -p "butHere'sMyNumberS0CallMeMaybe"
info:    Executing command vm create
+ Looking up the VM "ahmet-testvm"
info:    Using the VM Size "Standard_A1"
warn:    The image "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB" will be used for VM
info:    The [OS, Data] Disk or image configuration requires storage account
+ Retrieving storage accounts
info:    Could not find any storage accounts in the region "westus", trying to create new one
+ Creating storage account "cli9d0ca3da108a9c0114314" in "westus"
+ Looking up the storage account cli9d0ca3da108a9c0114314
error:   Either NIC Id or NIC name is required
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   vm create command failed

➜  ~  azure vm create "ahmet-rg" "ahmet-testvm" "westus" "Linux" --image-name "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB" -u azureuser -p "butHere'sMyNumberS0CallMeMaybe"

➜  ~  azure vm create "ahmet-rg" "ahmet-testvm" "westus" "Linux" --image-name "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB" -u azureuser -p "butHere'sMyNumberS0CallMeMaybe"
info:    Executing command vm create
+ Looking up the VM "ahmet-testvm"
info:    Using the VM Size "Standard_A1"
warn:    The image "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB" will be used for VM
info:    The [OS, Data] Disk or image configuration requires storage account
+ Retrieving storage accounts
info:    Could not find any storage accounts in the region "westus", trying to create new one
+ Creating storage account "cli7933602829395d7914314" in "westus"
+ Looking up the storage account cli7933602829395d7914314
error:   Either NIC Id or NIC name is required
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   vm create command failed

➜  ~  azure vm create "ahmet-rg" "ahmet-testvm" "westus" "Linux" --image-name "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB" -u azureuser -p "butHere'sMyNumberS0CallMeMaybe"
info:    Executing command vm create
+ Looking up the VM "ahmet-testvm"
info:    Using the VM Size "Standard_A1"
warn:    The image "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB" will be used for VM
info:    The [OS, Data] Disk or image configuration requires storage account
+ Retrieving storage accounts
info:    Could not find any storage accounts in the region "westus", trying to create new one
+ Creating storage account "cli11afe37194c78fcd14314" in "westus"
+ Looking up the storage account cli11afe37194c78fcd14314
error:   Either NIC Id or NIC name is required
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   vm create command failed

```

**Comment by anuchandy** [comment] 2015-05-12 22:31
This is fixed and will be available in the next CLI update https://github.com/MSOpenTech/azure-xplat-cli-pr/issues/520

**Comment by ahmetalpbalkan** [comment] 2015-05-12 22:33
@anuchandy thanks for the info. Let's close when the fix is publicly out.

**Comment by anuchandy** [comment] 2015-05-12 22:36
@ahmetalpbalkan the second link https://github.com/MSOpenTech/azure-xplat-cli/tree/dev is public. 

The first link was same issue we tracked in pr.

**Comment by HimanshuBri** [comment] 2015-05-15 10:27
@anuchandy  @ahmetalpbalkan It is working fine now
<pre>
<code>
C:\May\15May\azure-xplat-cli-dev>node bin/azure vm create armresgrp15M vmTest1 eastus Windows -q MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:2.0.201502 -f nic7 -u azureuser -p
 Brillio@2015
info:    Executing command vm create
+ Looking up the VM "vmTest1"
info:    Using the VM Size "Standard_A1"
warn:    The image "MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:2.0.201502" will be used for VM
info:    The [OS, Data] Disk or image configuration requires storage account
+ Retrieving storage accounts
info:    Using the storage account "20c78896259a917e68f31429" in "eastus"
+ Looking up the NIC "nic7"
info:    An nic with given name "nic7" not found, creating a new one
error:   The parameters vnetName is required
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   vm create command failed


</code>
</pre>

**Comment by anuchandy** [comment] 2015-05-15 17:00
Thank you @HimanshuBri for validating. Will close this once PR merged to upstream

**Comment by babumuralidharan** [comment] 2015-06-09 18:10
fix part of sprint 49

**Closed by babumuralidharan** 2015-06-09 18:10 UTC
Labels: IAAS, Ready For Test

**Comment by CelsoSantos** [comment] 2016-02-24 19:44
I'm using the latest version and this still happens, at least on OS X.

Is there any work-around? This is really frustrating...

**Comment by julkiewicz** [comment] 2016-04-15 20:25
There is a work-around. Create "Network interface" from azure portal. Then find it's resource ID. Should be something like /subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Network/networkInterfaces/<nic-id>. Then specify it during creation using -D option.

**Comment by ahmetalpbalkan** [comment] 2016-04-15 20:38
@julkiewicz you're on the wrong issue?

**Comment by julkiewicz** [comment] 2016-04-15 20:39
I don't think so. I'm referring to the comment by the collegue CelsoSantos above. I got the very same problem and what I posted seems to be the work-around he was asking for.

**Comment by julkiewicz** [comment] 2016-04-15 20:41
Actually yeah, you're right, I meant to post that here: https://github.com/Azure/azure-xplat-cli/issues/1760

**Comment by CelsoSantos** [comment] 2016-04-15 20:43
To be honest I had forgotten I had even opened the issue.

But I can confirm that I ended up creating everything through the portal
first and then associating the previously created items (storage account,
NIC, etc) via cli to the new VM (created through cli)
On 15 Apr 2016 21:39, "Juliusz Kopczewski" <notifications@github.com> wrote:

I don't think so. I'm referring to the comment by the collegue CelsoSantos
above. I got the very same problem and what I posted seems to be the
work-around he was asking for.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/Azure/azure-xplat-cli/issues/1761#issuecomment-210637096>

**Comment by wangjj1989** [comment] 2016-09-14 06:17
Hi, 
I follow steps in [https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-upload-vhd/](url) to create a Linux VM.
I have create a storage account and upload the vhd to my storage account.
Then I use follow command to create new vm:
`azure vm create testvm1 -l " janpaneast"  --resource-group res-group -Q xxx -o xxx -f testvm1-nic`

But I find that it always create a new storage account, who can tell me why?
