### ISSUE TITLE
`azure vm list-usage` doesn't work

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2588] opened 2016-03-01 00:11 UTC
CLI Version: **0.9.15 (node: 4.2.3)**
OS Type: Mac / Win / **Linux** (Ubuntu, RedHat, etc.)
Installation via:  **nix**

Mode: **ARM**

Description:
`azure vm list-usage` just doesn't work.

```
$ azure vm list-usage
info:    Executing command vm list-usage
Location: westus
error:   Cannot read property 'list' of undefined
info:    Error information has been recorded to /home/cole/.azure/azure.err
error:   vm list-usage command failed

$ azure vm list-usage --location westus
info:    Executing command vm list-usage
error:   Cannot read property 'list' of undefined
info:    Error information has been recorded to /home/cole/.azure/azure.err
error:   vm list-usage command failed
```

**Comment by yugangw-msft** [comment] 2016-03-01 00:36
@colemickens if you installed from npm, please get rid of ~/.streamline, and try again.

**Comment by colemickens** [comment] 2016-03-01 00:40
I didn't install from streamline.

**Comment by colemickens** [comment] 2016-03-01 00:40
I didn't install from `npm`.

The package was built by pulling packages from `npm` though...

**Comment by colemickens** [comment] 2016-03-01 00:40
Did it anyway; no effect.

**Comment by amarzavery** [comment] 2016-03-01 08:03
This is a bug indeed. The usageOperations werent ported to Autorest generated client. This bug happened due to a test debt.

After modifying this function in lib/commands/arm/vm/vmClient._js file, the command worked.

```
listComputeUsage: function(location, options, _) {
    var subscription = profile.current.getSubscription(this.subscription);
    var client = utils.createComputeManagementClient(subscription);

    var usageResult = client.usageOperations.list(location, _);
    var output = this.cli.output;
    if(!usageResult || usageResult.length === 0) {
      if (output.format().json) {
        output.json([]);
      } else {
        output.warn($('No compute usage information found'));
      }

      return;
    }
    
    this.cli.interaction.formatOutput(usageResult, function (outputData) {
      output.table(outputData, function (row, item) {
        row.cell($('Name'), item.name.localizedValue);
        row.cell($('Unit'), item.unit);
        row.cell($('CurrentValue'), item.currentValue);
        row.cell($('Limit'), item.limit);
      });
    });
  },
```

The output is displayed correctly:
```
Amars-MacBook-Air:azure-xplat-cli amzavery$ node bin/azure vm list-usage westus
info:    Executing command vm list-usage
data:    Name                        Unit   CurrentValue  Limit
data:    --------------------------  -----  ------------  -----
data:    Availability Sets           Count  0             347987986986
data:    Total Regional Cores        Count  0             6507456456   
data:    Virtual Machines            Count  0             88098789
data:    Virtual Machine Scale Sets  Count  0             9009090   
info:    vm list-usage command OK
```

**Comment by amarzavery** [comment] 2016-03-01 08:04
@huangpf - This should be fixed at the earliest with a test recording to avoid regression.

**Comment by huangpf** [comment] 2016-03-01 18:30
I tested the ```0.9.16``` build, and it seems to be working fine. I had updated the tests for it as well.

Please refer to: https://github.com/Azure/azure-xplat-cli/pull/2592

**Closed** 2016-03-01 19:20 UTC
