### ISSUE TITLE
ASM: azure vm create with vnet requires --location but ignores --location

### ISSUE THREAD

**Issue by magaal** [Azure/azure-xplat-cli#1628] opened 2015-03-11 16:30 UTC
azure vm create appears to require --location or --affinity-group even if a vnet is specified, but then warns that location will be ignored. Is it possible to enhance the command to ignore location if a vnet is specified?

May be similar to issue #1355 ?

**Comment by ruslangabitov** [comment] 2015-05-28 00:02
Hello @magaal, I was not able to reproduce this issue using latest release. We had this issue in our previous versions, but looks like it was fixed in 0.8.16 (https://github.com/Azure/azure-xplat-cli/releases/tag/v0.8.16-March2015)
Can you please try it again using latest code?
If it is still not working, can you specify command that you are trying to run?

**Comment by anuchandy** [comment] 2015-06-17 00:56
Closing this, this is fix is available starting from v0.8.16

**Closed by anuchandy** 2015-06-17 00:56 UTC
Labels: IAAS, P1, Ready For Test
