### ISSUE TITLE
Export hangs: azure datalake store filesystem export

### ISSUE THREAD

**Issue by mweaverh** [Azure/azure-xplat-cli#2312] opened 2015-11-20 20:55 UTC
This just hangs (8 minutes+), and pegs a cpu at 100%:
```
% azure datalake store filesystem export -vv mswazdltry1adl /TestFolder/SearchLog_FROM-Data-Lake.txt ./slfdl.txt
info:    Executing command datalake store filesystem export
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: {
silly:           Content-Type: 'application/json; charset=utf-8',
silly:           User-Agent: 'Azure SDK - Microsoft.Azure.Management.DataLake.StoreFileSystem 0.9.4-preview ',
silly:           useragent: 'Azure SDK - Microsoft.Azure.Management.DataLake.StoreFileSystem 0.9.4-preview '
silly:       },
silly:       url: 'https://mswazdltry1adl.azuredatalakestore.net/webhdfs/v1/%2FTestFolder%2FSearchLog_FROM-Data-Lake.txt?op=GETFILESTATUS&api-version=2015-10-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           content-length: '225',
silly:           date: 'Fri, 20 Nov 2015 20:45:33 GMT',
silly:           server-perf: '[0497e07d5e4841e3b215a7476f463f20][ AuthTime::1698.80147246569::PostAuthTime::31482.1444075344 ][IsExist :: 00:00:000 ms]%0a[HdfsGetFileStatus :: 00:00:124 ms]%0a[SS Response Process :: 00:00:000 ms]%0a[GETFILESTATUS :: 00:00:124 ms]%0a',
silly:           cache-control: 'no-cache',
silly:           x-ms-request-id: '0497e07d-5e48-41e3-b215-a7476f463f20',
silly:           x-content-type-options: 'nosniff',
silly:           content-type: 'application/json; charset=utf-8',
silly:           strict-transport-security: 'max-age=15724800; includeSubDomains',
silly:           expires: '-1',
silly:           set-cookie: [ 'UserPrincipalSession=ff74a2c7-59e5-43c5-b284-4af7c0160685; path=/; secure; HttpOnly' ],
silly:           pragma: 'no-cache'
silly:       },
silly:       body: '{"FileStatus":{"length":3500,"pathSuffix":"","type":"FILE","blockSize":268435456,"accessTime":1448051554853,"modificationTime":1448051554927,"replication":0,"permission":"777","owner":"NotSupportYet","group":"NotSupportYet"}}'
silly:   }
verbose: Downloading file /TestFolder/SearchLog_FROM-Data-Lake.txt to the specified location: ./slfdl.txt
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { User-Agent: 'Azure SDK - Microsoft.Azure.Management.DataLake.StoreFileSystem 0.9.4-preview ', useragent: 'Azure SDK - Microsoft.Azure.Management.DataLake.StoreFileSystem 0.9.4-preview ' },
silly:       url: 'https://mswazdltry1adl.azuredatalakestore.net/webhdfs/v1/%2FTestFolder%2FSearchLog_FROM-Data-Lake.txt?op=OPEN&offset=0&length=3500&api-version=2015-10-01-preview',
silly:       encoding: null
silly:   }
silly:   returnObject

^C
dev/azure% uname -a                                                           (12:54)
Linux Ubu14Msw4-M4800 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Import seems to work fine.
Thanks for taking a look.

**Comment by amarzavery** [comment] 2015-11-25 19:01
@begoldsm - Can you please take a look at this Datalake issue?

**Comment by begoldsm** [comment] 2015-12-01 01:28
Yes looking today.

Thanks!
Ben

On Nov 25, 2015, at 11:01 AM, Amar Zavery <notifications@github.com<mailto:notifications@github.com>> wrote:


@begoldsm<https://github.com/begoldsm> - Can you please take a look at this Datalake issue?

-

**Comment by begoldsm** [comment] 2015-12-01 01:36
@mweaverh how big is the file you are trying to download? The upload/download logic is currently sequential so if you are trying to download a large file it will take a very long time. There is an improvement scheduled to increase the performance for ingress and egress through the xplat cli in our next development push.

If this is happening with even small files (say, < 10MB) then please let me know and I will investigate further.

**Comment by begoldsm** [comment] 2015-12-01 01:37
@mweaverh I just realized that the file is quite small. I am continuing to investigate now.
Thanks!

**Comment by amarzavery** [comment] 2016-02-16 03:01
@begoldsm - Any update on this issue?

**Comment by begoldsm** [comment] 2016-02-16 06:36
I'm going to try and repro this with the new autorest framework, since it appears to be a problem inside of the 'request' module causing a hang with byte content on Linux machines.

Thanks!
Ben

On Feb 15, 2016, at 7:01 PM, Amar Zavery <notifications@github.com<mailto:notifications@github.com>> wrote:


@begoldsm<https://github.com/begoldsm> - Any update on this issue?

-

**Comment by begoldsm** [comment] 2016-04-08 18:23
@amarzavery I just tested this out with the latest Xplat CLI on an ubuntu VM and I believe it is now resolved. The underlying issue appeared to be related to our logging logic when dealing with large amounts of data in the request/response.
@mweaverh can you test this out with the latest (0.9.19) on your side and confirm the issue is resolved and let us know?

**Comment by amarzavery** [comment] 2016-04-18 22:54
Closing this as the issue seems to be resolved.

**Closed by amarzavery** 2016-04-18 22:54 UTC
