### ISSUE TITLE
correct syntax for creating linux vms 

### ISSUE THREAD

**Issue by lijukj** [Azure/azure-xplat-cli#2956] opened 2016-06-23 23:05 UTC
CLI Version: 
# azure --version
0.10.1 (node: 0.10.25)
# npm --version
1.3.10
# node --version
v0.10.25
OS Type: Description:	Ubuntu 14.04.4 LTS
Installation via:  npm 

Mode:  ASM**

Environment: **AzureCloud
Description:
Unable to ssh to the vm using password.

Steps to reproduce:
1) Run 
azure vm create test69rclivm  rhel71 --location 'Southeast Asia' --userName testuser --password 'R2111111'

2) Then try to ssh to it
lijumac-2:~ likj$ ssh testuser@13.67.58.13
The authenticity of host '13.67.58.13 (13.67.58.13)' can't be established.
ECDSA key fingerprint is SHA256:fiVytx50xitczg7LCDZz9L0Nxi8T/50fZnBn3OdKWfI.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '13.67.58.13' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

Is '--ssh' flag mandatory to enable ssh to the VM?

**Comment by huangpf** [comment] 2016-06-25 10:45
Since it asked a password input, so I think this is currently by design to use password, if the SSH option not specified. Please help confirm if ```--ssh``` works for you.

**Comment by paulmey** [comment] 2016-06-27 20:17
Duplicate of https://github.com/Azure/azure-xplat-cli/issues/2859 ?

**Comment by lijukj** [comment] 2016-07-01 16:41
@paulmey - yes duplicate of #2859 
@huangpf - you might want to test this or refer to #2859

**Closed** 2016-07-01 16:42 UTC
Labels: ASM, IAAS, P3
