### ISSUE TITLE
Can not create availset with user defined Update domain count

### ISSUE THREAD

**Issue by vfordpivotal** [Azure/azure-xplat-cli#2648] opened 2016-03-17 17:50 UTC
Via the web portal the number of fault domains and update/upgrade domains can be configured during the creation of the availability set. CLI doesn't appear to provide this option and only creates availability set with default options.

$ **azure availset create --help**
help:    Creates an availability set within a resource group
help:
help:    Usage: availset create [options] <resource-group> <name> <location> [tags]
help:
help:    Options:
help:      -h, --help                             output usage information
help:      -v, --verbose                          use verbose output
help:      -vv                                    more verbose with debug output
help:      --json                                 use json output
help:      -g, --resource-group <resource-group>  the resource group name
help:      -n, --name <name>                      the availability set name
help:      -l, --location <location>              the location
help:      -t, --tags <tags>                      the semicolon separated list of tags
help:      -s, --subscription <subscription>      the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)
CLI Version: **0.9.X**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm / brew / win-or-mac installer / docker / github repo

$ **azure availset create sample availtestgfe westus**
info:    Executing command availset create
+ Looking up the availability set "availtestgfe"
+ Creating availability set "availtestgfe"
info:    availset create command OK

$ **azure availset list**
info:    Executing command availset list
Resource group name: sample
+ Getting availiability sets
data:    Name          Location  Update domain count  Fault domain count
data:    ------------  --------  -------------------  ------------------
data:    availtestgfe  westus    5                    3
info:    availset list command OKMode:ARM

$ **azure --version**
0.9.16 (node: 4.2.4)

**Comment by amarzavery** [comment] 2016-03-18 03:39
@huangpf , @sauryadas - Can you look into this?

**Comment by huangpf** [comment] 2016-03-18 06:04
@amarzavery Ack. Looks like a gap to fill.

**Comment by sauryadas** [comment] 2016-04-29 02:44
@huangpf - looks like you made commits for this issue . Is this fixed yet?

**Comment by amarzavery** [comment] 2016-07-15 21:30
Looks like the issue is fixed. Hence closing it. Feel free to reopen if required.

**Closed by amarzavery** 2016-07-15 21:30 UTC
Labels: ARM, IAAS
